# Generated by Django 5.2.15 on 2026-07-07 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_phoneotp"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="phoneotp",
            new_name="accounts_ph_phone_ee60bf_idx",
            old_name="accounts_ph_phone_pur_used_idx",
        ),
    ]
