# Generated by Django 5.2.15 on 2026-07-20 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_listing_chat_and_notifications"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usernotification",
            new_name="accounts_us_user_id_587a4e_idx",
            old_name="accounts_us_user_id_8a0d0d_idx",
        ),
    ]
