# Generated by Django 5.2.15 on 2026-07-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        ("minerals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_sw", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("polygon", "Polygon"),
                            ("point", "Point"),
                            ("line", "Line"),
                        ],
                        max_length=10,
                    ),
                ),
                ("z_index", models.IntegerField(default=0)),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False, help_text="Visible to free-tier users"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "style",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="fill, stroke, strokeWidth, hatch pattern",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("current_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_layers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mineral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="minerals.mineral",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="layers",
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "ordering": ["z_index", "name"],
                "unique_together": {("mineral", "slug")},
            },
        ),
        migrations.CreateModel(
            name="MapFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geometry", models.JSONField(help_text="GeoJSON geometry object")),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="maps.maplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LayerUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="layer_imports/")),
                ("file_type", models.CharField(default="geojson", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="maps.maplayer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LayerVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("changelog", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, upload_to="layer_uploads/")),
                ("feature_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="maps.maplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("layer", "version_number")},
            },
        ),
    ]
