# Generated by Django 5.2.15 on 2026-07-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0012_alter_maplayer_buffer_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maplayer",
            name="is_preview",
            field=models.BooleanField(
                default=False,
                help_text="Show this layer on the free (unpaid) map and legend.",
            ),
        ),
    ]
