# Generated by Django 5.2.15 on 2026-07-11 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0013_alter_maplayer_is_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="maplayer",
            name="heatmap_weight",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Relative strength (0–10) when this layer contributes to a mineral heatmap. Intersection class (3/2/1 geometries) is scaled by the mean weight of contributing layers.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
