# Generated by Django 5.2.15 on 2026-07-13 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacelisting",
            name="document_download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="map_click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="terra_summary_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="geometry",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="GeoJSON Point, MultiPoint, Polygon, or MultiPolygon for the marketed area.",
            ),
        ),
        migrations.CreateModel(
            name="ListingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("map_click", "Map click"),
                            ("document_download", "Document download"),
                            ("terra_summary", "Terra summary"),
                        ],
                        max_length=32,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="marketplace.marketplacelisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "kind", "created_at"],
                        name="marketplace_listing_0ee3c3_idx",
                    ),
                    models.Index(
                        fields=["kind", "created_at"],
                        name="marketplace_kind_b4a1a7_idx",
                    ),
                ],
            },
        ),
    ]
