# Generated by Django 5.2.15 on 2026-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_primary_other_minerals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplacelisting",
            name="commodity_labels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Derived display tags: primary_mineral first, then other_minerals.",
            ),
        ),
    ]
