# Generated by Django 5.2.15 on 2026-07-20 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0007_optional_listing_conversations"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="listingconversation",
            new_name="marketplace_listing_e2f2d6_idx",
            old_name="marketplace_listing_6d0a8b_idx",
        ),
        migrations.RenameIndex(
            model_name="listingconversation",
            new_name="marketplace_buyer_i_e3296d_idx",
            old_name="marketplace_buyer_i_5f0d1a_idx",
        ),
        migrations.RenameIndex(
            model_name="listingmessage",
            new_name="marketplace_convers_bab152_idx",
            old_name="marketplace_convers_0b0f2c_idx",
        ),
    ]
