# Generated by Django 5.2.15 on 2026-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_chat_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="included_assistant_credits",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ask Terra AI credits included per calendar month (e.g. 3000 monthly plan, 5000 annual plan).",
            ),
        ),
    ]
