# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_alter_subscriptionplan_included_assistant_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="includes_saved_explorations",
            field=models.BooleanField(
                default=False,
                help_text="Subscribers can save drawn exploration areas (points/lines/polygons) to their account.",
            ),
        ),
    ]
