# Generated by Django 5.2.15 on 2026-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0014_heatmap_weight_and_associated_layers"),
        ("minerals", "0003_mineral_color_rgba"),
    ]

    operations = [
        migrations.AddField(
            model_name="mineral",
            name="associated_layers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Extra map layers (structures, points, etc.) included when this commodity is selected for heatmap / catalog overlay.",
                related_name="associated_minerals",
                to="maps.maplayer",
            ),
        ),
    ]
