# Generated by Django 5.2.15 on 2026-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_remove_selcom_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription"),
                    ("download", "Report Download"),
                    ("license", "License Agreement"),
                    ("aerial", "Aerial analysis extension"),
                ],
                max_length=20,
            ),
        ),
    ]
