# Generated by Django 5.2.15 on 2026-07-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0002_country_focus_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Country"), (1, "Region"), (2, "District")]
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_sw", models.CharField(blank=True, max_length=200)),
                ("code", models.CharField(max_length=64)),
                (
                    "geometry",
                    models.JSONField(help_text="GeoJSON Polygon or MultiPolygon"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gadm", "GADM"),
                            ("admin_upload", "Admin upload"),
                            ("preset", "Preset"),
                        ],
                        default="preset",
                        max_length=20,
                    ),
                ),
                ("center_lat", models.FloatField(blank=True, null=True)),
                ("center_lng", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_boundaries",
                        to="geography.country",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="geography.adminboundary",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_boundaries",
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "admin boundaries",
                "ordering": ["level", "name"],
                "indexes": [
                    models.Index(
                        fields=["country", "level"],
                        name="geography_a_country_01e00d_idx",
                    )
                ],
                "unique_together": {("country", "level", "code")},
            },
        ),
    ]
