# Generated by Django 5.2.15 on 2026-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0003_admin_boundary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminboundary",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Country"), (1, "Region"), (2, "District"), (3, "Village")]
            ),
        ),
    ]
