# Generated by Django 5.2.15 on 2026-07-05 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0006_adminboundary_ward_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminboundary",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "geographic boundary",
                "verbose_name_plural": "geographic boundaries",
            },
        ),
    ]
