# Generated by Django 5.2.15 on 2026-07-16 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0009_country_coordinate_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "source_file",
                    models.FileField(blank=True, upload_to="geo_references/"),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("feature_count", models.PositiveIntegerField(default=0)),
                (
                    "bounds",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Bounding box: {"west", "south", "east", "north"}',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geo_references",
                        to="geography.country",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geo_reference_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "geo reference",
                "verbose_name_plural": "geo references",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeoReferenceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geometry", models.JSONField()),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "geo_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="geography.georeference",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
