# Generated by Django 5.2.15 on 2026-07-16 13:53

from django.db import migrations, models


def backfill_bboxes(apps, schema_editor):
    # Import after columns exist; uses live model helpers for geometry bbox.
    from apps.geography.geo_reference import backfill_geo_reference_feature_bboxes

    backfill_geo_reference_feature_bboxes()


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0010_geo_reference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="georeferencefeature",
            options={"ordering": []},
        ),
        migrations.AddField(
            model_name="georeferencefeature",
            name="max_lat",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="georeferencefeature",
            name="max_lng",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="georeferencefeature",
            name="min_lat",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="georeferencefeature",
            name="min_lng",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_bboxes, migrations.RunPython.noop),
    ]
