# Generated by Django 5.2.15 on 2026-07-07 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adevent",
            new_name="ads_adevent_ad_id_7e41d8_idx",
            old_name="ads_adevent_ad_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="adevent",
            new_name="ads_adevent_placeme_8e0668_idx",
            old_name="ads_adevent_place_idx",
        ),
    ]
