# Generated by Django 5.2.15 on 2026-07-03 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_assistant_credit_usage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assistantcreditusage",
            new_name="analytics_a_user_id_3d5425_idx",
            old_name="analytics_a_user_id_8a0f0d_idx",
        ),
        migrations.RenameIndex(
            model_name="assistantcreditusage",
            new_name="analytics_a_session_f2b2c6_idx",
            old_name="analytics_a_session_6c2b1a_idx",
        ),
        migrations.RenameIndex(
            model_name="assistantcreditusage",
            new_name="analytics_a_subscri_dd3f26_idx",
            old_name="analytics_a_subscri_4e8f2c_idx",
        ),
    ]
