# Generated by Django 5.2.15 on 2026-07-03 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_assistantchatthread"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assistantchatthread",
            new_name="analytics_a_user_id_390eaa_idx",
            old_name="analytics_a_user_id_chat_idx",
        ),
    ]
