# Generated by Django 5.2.15 on 2026-07-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_aerial_analysis_grant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantcreditusage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("map_insight", "Map insight"),
                    ("chat", "Chat message"),
                    ("report_export", "Insight report export"),
                ],
                max_length=20,
            ),
        ),
    ]
