# Generated by Django 5.2.15 on 2026-07-06 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0007_mineralexplorationlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mineralexplorationlog",
            new_name="analytics_m_user_id_e296cf_idx",
            old_name="analytics_m_user_id_4b0d0a_idx",
        ),
        migrations.RenameIndex(
            model_name="mineralexplorationlog",
            new_name="analytics_m_user_id_e1c661_idx",
            old_name="analytics_m_user_id_8f2c1d_idx",
        ),
    ]
