# Generated by Django 5.2.15 on 2026-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analytics",
            "0008_rename_analytics_m_user_id_4b0d0a_idx_analytics_m_user_id_e296cf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantcreditusage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("map_insight", "Map insight"),
                    ("chat", "Chat message"),
                    ("report_export", "Insight report export"),
                    ("report_chat", "Report PDF chat"),
                    ("exploration_generate", "Exploration report generate"),
                    ("exploration_refine", "Exploration report refine"),
                    ("exploration_export", "Exploration report export"),
                ],
                max_length=20,
            ),
        ),
    ]
