# Generated by Django 5.2.15 on 2026-07-06 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_reports_module_expansion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportdocumentchunk",
            new_name="reports_rep_report__799376_idx",
            old_name="reports_rep_report__a8f3c2_idx",
        ),
    ]
