# Generated by Django 5.2.15 on 2026-07-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reports",
            "0003_rename_reports_rep_report__a8f3c2_idx_reports_rep_report__799376_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("ai_generated", "Platform generated"),
                    ("user_generated", "User generated"),
                ],
                default="ai_generated",
                max_length=20,
            ),
        ),
    ]
